package com.revature.flash_back_api.util.exceptions;

public class DataSourceException extends RuntimeException {
    public DataSourceException(String message, Throwable cause) {
        super(message, cause);
    }
}

